### ISSUE TITLE
Typo in variable and resource name

### ISSUE THREAD

**Issue by LuigiClemente-Awin** [cloudposse/terraform-aws-firewall-manager#15]
I suspect you used the word "shiled_advanced" instead of "shield_advanced" everywhere in the code and in the variables.
No typo check at all?

Best,

Luigi

**Comment by nitrocode** [comment]
@LuigiClemente-Awin nice catch

https://github.com/cloudposse/terraform-aws-firewall-manager/blob/0460e1f9e64ff1b54bed60063d1d6f60aaffa49a/variables.tf#L137

please submit a pull request and we'll review it
