### ISSUE TITLE
Error: missing provider provider["registry.terraform.io/hashicorp/aws"].service

### ISSUE THREAD

**Issue by mattt-liu** [cloudposse/terraform-aws-firewall-manager#7]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
When running `terraform plan` inside the module, Terraform throws the followiing error:
```
Error: missing provider provider["registry.terraform.io/hashicorp/aws"].service
```

## Expected Behavior
Terraform should display a summary of the actions it will execute based on the module's inputs.

## Steps to Reproduce
Checkout [this branch](https://github.com/cloudposse/terraform-aws-firewall-manager/pull/8).

Inside the `/examples/complete` directory run the following:
```
terraform init
```

Then run:
```
terraform plan
```
The console then throws the following error:
```
╷
│ Error: missing provider provider["registry.terraform.io/hashicorp/aws"].service
│ 
│ 
╵
```

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: macOS Big Sur
 - Version 11.2.3

**Comment by nitrocode** [comment]
@mattt-liu this was provider was added to the example in pr https://github.com/cloudposse/terraform-aws-firewall-manager/pull/9. are you still seeing an issue?
